const translations = {
  en: {
    Menu: "MENU",
    Bar: "BAR",
    Tea_Card: "TEA MENU",
    Wine_card: "WINE CARD",
    CHI_SOUCE_EGGPLANT: "CHI SOUCE EGGPLANT",
    new_in: "NEW IN",
    nigiri: "SUSHI NIGIRI",
    sashimi: "SASHIMI",
    gunkan: "GUNKAN",
    temaki: "ТЕМАКІ",
    rolls: "ROLLS",
    salads: "SALADS",
    coldap: "COLD APPETIZERS",
    soups: "SOUPS",
    hotap: "HOT APPETIZERS",
    hotsea: "HOT SEAFOOD APPETIZERS",
    dimsum: "DIM SUM",
    gyoza: "GYOZA",
    sides: "SIDES",
    hotd: "HOT DISHES",
    fish: "FISH",
    desserts: "DESSERTS",
    candie: "CANDIES",
    new2: "NEW IN",
    muss: "MUSSELS IN WASABI SAUCE",
    eggpl: "SALAD WITH EGGPLANTS AND TOMATOES",
    CIBAS: "CHILEAN SEABASS WITH MISO SAUCE",
    SWEETPOTATO: "SWEET POTATO FRIES WITH TRUFFLE SAUCE AND PARMESAN",
    MISOSPICY: "MISO SPICY SOUP",
    nig0: "SUSHI NIGIRI",
    nig1: "SALMON",
    nig2: "TUNA",
    nig3: "TOBIKO (flying fish roe)",
    nig4: "TIGER PRAWN",
    nig5: "EEL",
    nig6: 'CRISPY RICE WITH SPICY TUNA <img class="spicy" src="img/Spicy.svg" style="padding-left:5px;">',
    nig6des: "Tuna, cherry tomato, shallot, tobiko (flying fish roe), Japanese mayonnaise, Guilin chili",
    nig7: 'CRISPY RICE WITH SPICY SALMON <img class="spicy" src="img/Spicy.svg" style="padding-left:5px;">',
    nig7des: "Salmon, cherry tomato, shallot, tobiko (flying fish roe), Japanese mayonnaise, Guilin chili",
    sash0: "SASHIMI",
    sash1: "SALMON",
    sash2: "EEL",
    sash3: "TUNA",
    sash4: "SCALLOP",
    sash5: "TIGER PRAWN",
    gunk0: "GUNKAN",
    gunk1: "SALMON",
    gunk1des: "Salmon, tobiko (flying fish roe), Japanese mayonnaise",
    gunk2: "TUNA",
    gunk2des: "Tuna, tobiko (flying fish roe), Japanese mayonnaise",
    gunk3: "TIGER PRAWN",
    gunk3des: "Prawn, tobiko (flying fish roe), Japanese mayonnaise, avocado",
    gunk4: "SCALLOP",
    gunk4des: "Scallop, tobiko (flying fish roe), Japanese mayonnaise",
    gunk5: "CRAB",
    tem0: 'TEMAKI (HAND ROLL) <br> IN NORI SHEET/IN SOY PAPER',
    tem1: "SALMON",
    tem1des: "Salmon, tobiko (flying fish roe), Japanese mayonnaise",
    tem2: "TUNA",
    tem2des: "Tuna, tobiko (flying fish roe), Japanese mayonnaise",
    tem3: "TIGER PRAWN",
    tem3des: "Prawn, tobiko (flying fish roe), Japanese mayonnaise",
    tem4: "SCALLOP",
    tem4des: "Scallop, tobiko (flying fish roe), Japanese mayonnaise",
    tem5: "CRAB",
    rol0: "ROLLS",
    rol1: "EEL ROLL",
    rol1des: "Eel, avocado, cucumber, sesame, unagi sauce",
    rol2: "PHILADELPHIA DE LUXE",
    rol2des: "Salmon, Philadelphia cream cheese, eel, avocado",
    rol3: "CLASSIC PHILADELPHIA",
    rol3des: "Salmon, Philadelphia cream cheese, avocado", 
    rol4: "GOLDEN DRAGON",
    rol4des: "Eel, tuna, tobiko (flying fish roe),unagi sauce, sesame ",
    rol5: "NORWEGIAN SALMON WITH TIGER PRAWN",
    rol5des: "Tempura prawns, avocado, salmon, truffle sauce",
    rol6: "CALIFORNIA WITH CRAB",
    rol6des: "Crab meat, avocado, cucumber, tobiko (flying fish roe), Japanese mayonnaise",
    rol7: "CRUNCH ROLL WITH PRAWN",
    rol7des: "Prawn, cucumber, unagi sauce, Japanese mayonnaise, tobiko (flying fish roe), tempura",
    rol8: "CRAB AND AVOCADO ROLL",
    rol8des: "Crab meat, tobiko (flying fish roe), avocado, unagi sauce",
    rol9: "FUTOMAKI ROLL",
    rol9des: "Tempura prawn, eel, salmon, Philadelphia cream cheese, tobiko (flying fish roe)",
    rol10: "CALIFORNIA ROLL WITH SALMON",
    rol10des: "Salmon, tobiko (flying fish roe), truffle sauce, cucumber, avocado",
    rol11: "MOON ROLL",
    rol11des: "Smoked salmon, Philadelphia cream cheese, avocado, cucumber, tobiko (flying fish roe)",
    rol12: "DOUBLE FISH ROLL",
    rol12des: "Salmon, Philadelphia cream cheese, avocado",
    sal0: "SALADS",
    sal1: "HIYASHI WAKAME SALAD WITH NUT SAUCE",
    sal2: 'WARM THAI-STYLE VEAL SALAD <img class="spicy" src="img/Spicy.svg"style="padding-left: 5px; ">', 
    sal2des: "Mixed greens, bell pepper, shiitake mushrooms, tender veal, soybean sprouts, chili pepper, ginger syrup",
    sal3: "SALMON SALAD",
    sal3des: "Salmon tataki, celery, apple, peanuts, mixed greens, garlic chips, signature sauce",
    sal4: "MAKOTO SALAD",
    sal4des: "Crab meat, wasabi sauce, cucumber, avocado",
    sal5: "ARUGULA & PRAWNS",
    sal5des: "Prawns, cherry tomatoes, walnuts, signature sauce",
    sal6: "EEL AND PEAR SALAD",
    sal6des: "Eel, avocado, spicy pear, spinach, nut sauce, walnuts",
    sal7: "SEAFOOD AND FRUITS SALAD",
    sal7des: "Prawns, salmon, squid, seasonal fruit, celery, bell pepper, basil, carrot, signature sauce",
    coldap0: "COLD APPETIZERS",
    coldap1: "SALMON TARTARE WITH GUACAMOLE",
    coldap1des: "Salmon, Japanese mayonnaise, avocado, cherry tomato, microgreens, tobiko (flying fish roe), yuzu",
    coldap2: "AZUMA TARTARE",
    coldap2des: "Salmon, tuna, yuzu guacamole, Japanese mayonnaise, cherry tomato, tobiko (flying fish roe), prawn chips",
    coldap3: "SCALLOP TARTARE",
    coldap3des: "Fresh scallop, Japanese mayonnaise, tobiko (flying fish roe), avocado, microgreens, chilli pepper",
    coldap4: "MARINATED VEAL TARTARE",
    coldap5: "VEGETABLES WITH NUT SAUCE",
    soup0: "SOUPS",
    soup1: "MISO SOUP",
    soup1des: "Rich broth, salmon, tofu cheese, shiitake, wakame, sesame, green onion",
    soup2: '* SEAFOOD SOUP WITH COCONUT MILK <img src="img/Extra.svg" style="padding-left: 5px;">',
    soup2des: "Coconut milk, tiger prawn, redfish, galangal, lime leaf, chili pepper, lemongrass, mushrooms, steamed rice",
    soup3: "* PHO BO",
    soup3des: "Vietnamese spiced soup with veal and noodles",
    soup4: 'CRAB SOUP "KANI NABE"',
    soup5: "* TOMATO SEAFOOD SOUP",
    soup5des: "Fish broth, spicy tomato sauce, scallop, pike perch, tiger prawn, salmon, sea bass, squid",
    hotap0: "HOT APPETIZERS",
    hotap1: "VEGETABLE SPRING ROLL",
    hotap1des: "Cabbage, carrot, champignons, onion sauce",
    hotap2: "DUCK SPRING ROLL",
    hotap2des: "Peking duck, carrot, celery root, shiitake mushrooms, leek, bell pepper, hoisin sauce",
    hotap3: 'EDAMAME <img class="spicy" src="img/Spicy.svg"style="padding-left: 5px; ">',
    hotap3des: 'Japanese soybeans, sea salt <br> "spicy / salted" on request',
    dimsum0: "DIM SUM NEW STYLE",
    dimsum1: "SIOMAI WITH SCALLOP AND SALMON",
    dimsum1des: "Scallop, salmon, coconut milk",
    dimsum2: "SIOMAI WITH SCALLOP AND RED CAVIAR",
    dimsum2des: "Scallop, tiger prawn, egg",
    dimsum3: "* SIOMAI WITH CRAB AND SPINACH",
    dimsum3des: "Crab, spinach, shrimp, ginger, oyster sauce, vegetable oil, sesame oil ",
    dimsum4: "DUMPLING WITH SALMON, GREEN ONION AND TOBIKO",
    dimsum4des: "Salmon, green onion",
    dimsum5: "DUMPLING WITH WHITE FISH",
    dimsum5des: "Pike perch, sea bass, dorado, Sriracha sauce",
    dimsum6: "ASSORTED DUMPLINGS",
    dimsum6des: "Spinach & shrimp, chicken & shiitake, salmon & green onion, white fish, duck",
    dimsum7: "DUMPLING WITH PRAWN AND LEEK",
    dimsum7des: "Fresh spinach, tiger prawn",
    dimsum8: "DUMPLING WITH RABBIT",
    hotapf0: "HOT SEAFOOD APPETIZERS",
    hotapf1: "EBI TEMPURA",
    hotapf1des: "Tiger prawn with traditional tempura sauce",
    hotapf2: "ALMOND PRAWNS",
    hotapf2des: "Tiger prawns in almond flakes",
    hotapf3: "SHRIMP POPCORN",
    gyoza0: "GYOZA",
    gyoza1: "GYOZA WITH CHICKEN",
    gyoza1des: "Chicken, leek, green onion",
    gyoza2: "GYOZA WITH PORK AND PRAWN",
    gyoza2des: "Pork, prawn, greens",
    gyoza3: "GYOZA WITH VEAL AND PRAWN",
    gyoza3des: "Veal, prawn, greens",
    side0: "SIDES",
    side1: "GOHAN",
    side1des: "Steamed white rice",
    side2: "YAKI MESHI",
    side2des: "Rice with shiitake mushrooms, champignons, carrot, green peas",
    side3: "CHINESE STYLE MUSHROOMS",
    side4: "TRUFFLE FRIES",
    side4des: "Truffle fries with Sichuan pepper and truffle sauce",
    side5: "GRILLED ASPARAGUS",

    hotdd0: "HOT DISHES",
    hotdd1: "VEAL WITH LOTUS ROOT",
    hotdd1des: "Lightly crispy veal cooked in a wok with teriyaki sauce and lotus root",
    hotdd2: "VEAL MEDALLIONS IN TERIYAKI SAUCE",
    hotdd3: "THAI-STYLE RICE",
    hotdd3des: "Rice with mixed greens, shrimp, soy sauce, wok-fried",
    hotdd4: "RICE NOODLES WITH TIGER PRAWNS AND VEGETABLES",
    hotdd5: 'RICE NOODLES WITH PEKING DUCK <img class="spicy" src="img/Spicy.svg" style="padding-left: 5px;">',
    hotdd6: 'KONGBAO <img class="spicy" src="img/Spicy.svg" style="padding-left: 5px;">',
    hotdd6des: "Chicken with vegetables and asparagus in chili sauce",
    hotdd7: "UDON NOODLES WITH VEAL",
    hotdd7des: "Udon noodles, veal, vegetables",
    hotdd8: "PRAWN IN SWEEAT AND SOUR SAUCE WITH PINEAPPLE",
    hotdd8des: "Tiger prawns stir-fried with vegetables and pineapple",
    hotdd9: "PEKING DUCK",
    hotdd9des: "Traditional duck, fresh cucumber, onion, pancakes, hoisin sauce",
    hotdd10: "TERIYAKI CHICKEN",
    hotdd11: "GRILLED PRAWN",
    hotdd12: "PERUVIAN RIBS",
    hotdd12des: " Mango, chili, spicy unagi sauce",
    hotdd13: "VEAL STEAK",
    hotdd14: "GRILLED SCALLOP",
    fisch0: "FISH",
    fisch1: "SALMON TERIYAKI",
    fisch1des: "Salmon pan-seared in teriyaki sauce",
    fisch2: "GRILLED PIKE PERCH WITH GARLIC SAUCE",
    fisch3: "DORADO TERIYAKI WITH CHERRY TOMATOES",
    dess0: "DESSERTS",
    dess1: 'FILO TUBES WITH BERRRIES AND MASCARPONE CREAM',
    dess2: "NUT AND CHOCOLATE DESERT",
    dess3: "SIGNATURE NAPOLEON",
    dess4: "YUZU CRÈME BRÛLÉE",
    dess5: "APPLE TART",
    dess6: "CHOCOLATE FONDANT",
    dess7: "LIME SORBET",
    dess8: "MANGO SORBET",
    dess9: "BERRY SORBET",
    dess10: "ASSORTED ICE CREAM",
    candie0: "CANDIES / CHOCOLATES",
    candie1: "ROYALTIN",
    candie2: "CHERRY IN CHOCOLATE",
    candie3: "HAZELNUT PRALINE",
    candie4: "BAMBOO",
    candie5: "DUBAI CHOCOLATE",
    s50ml : "50 ml",
    work1: "Working hours:",
    add1: "Address:",
    phone1: "Contact:",
    s11: "SAKE",
  s12: "VODKA",
  s13: "GRAPE VODKA",
  s14: "JAPAN GIN",
  s15: "GIN",
  s16: "TEQUILA",
  s17: "RUM",
  s18: "COGNAC",
  s19: "CALVADOS",
  s20: "JAPAN WHISKEY",
  s21: "AMERICAN WHISKEY",
  s22: "AMERICAN WHISKEY TENNESSEE",
  s23: "BOURBON",
  s24: "SCOTCH",
  s25: "SCOTCH SINGLE MALT",
  s26: "IRISH WHISKEY",
  s27: "LIQUEURS",
  s28: "BITTERS",
  s29: "VERMOUTH",
  s30: "SHOTS",
  s31: "BEER",
  s32: "ALCOHOL COCKTAILS",
  s33: "HOT BEVERAGES",
  s34: "ALCOHOL FREE DRINKS",
  s35: "FRESH",
  s36: "ALCOHOL FREE COCKTAILS",
  s37: "LEMONADES",
  s300ml: "330 ml",
  drink1: "Espresso / Decaf Espresso",
    drink2: "Americano / Decaf Americano",
    drink3: "Cappuccino / Decaf Cappuccino",
    drink4: "Latte Macchiato",
    drink5: "Matcha Latte (with plant-based milk)",
    drink6: "Doppio (with plant-based milk)",
    drink7: "Turkish Coffee",
    drink8: "Cocoa with Marshmallows",
    drink9: "Raf Coffee",
    drink9_desc: "Coffee whipped with cream and crème brûlée syrup",
    drink10: "Flat White",
    drink10_desc: "Double espresso, milk",
    drink11: "Espresso Tonic",
    drink11_desc: "Espresso, tonic, passion fruit syrup",
    drink12: "Mulled Wine (red/white)",
    drink12_desc: "Wine, honey, spices",
    drink13: "Mineral Water Aqua Panna",
    drink13_desc: "250 ml, still",
    drink14: "Mineral Water Rocchetta",
    drink14_desc: "500 ml, still or sparkling",
    drink15: "Mineral Water Evian",
    drink15_desc: "750 ml",
    drink16: "Mineral Water Perrier",
    drink16_desc: "330 ml",
    drink17: "Mineral Water Borjomi",
    drink17_desc: "500 ml",
    drink18: "Organic Fritz Cola Sugar Free",
    drink18_desc: "330 ml",
    drink19: "Coca-Cola, Sprite",
    drink19_desc: "250 ml",
    drink20: "Tonic Original",
    drink20_desc: "300 ml",
    drink21: "Juice Assortment",
    drink21_desc: "250 ml",
    juice1: "Pineapple Juice",
    juice1_desc: "300 ml",
    juice2: "Apple Juice",
    juice2_desc: "300 ml",
    juice3: "Carrot Juice",
    juice3_desc: "300 ml",
    juice4: "Grapefruit Juice",
    juice4_desc: "300 ml",
    juice5: "Orange Juice",
    juice5_desc: "300 ml",
    lemon1: "Bubble Gum–Strawberry Lemonade",
    lemon1_desc: "400 ml",
    lemon2: "Lychee–Raspberry Lemonade",
    lemon2_desc: "400 ml",
    lemon3: "Pear–Bergamot Lemonade",
    lemon3_desc: "400 ml",
    lemon4: "Pineapple–Apple Lemonade",
    lemon4_desc: "400 ml",
    lemon5: "Watermelon–Yuzu Lemonade",
    lemon5_desc: "400 ml",
    lemon6: "Cucumber–Passion Fruit Lemonade",
    lemon6_desc: "400 ml",
    lemon7: "Violet–Elderflower Lemonade",
    lemon7_desc: "400 ml",

    t1:  "REFRESHING TEA",
    t2:  "BLACK TEA",
    t3:  "JAPANESE TEA",
    t4:  "CHINESE ELITE TEAS",
    t5:  "TIED TEAS",
    t6:  "JASMINE TEA",
    t7:  "PUERA",
    t8:  "RED TEA",
    t9:  "HERBAL TEAS",
    t10: "FRUIT AND BERRY TEAS",
    t11: "EXOTIC TEAS",
    t12: "TEAS WITH ALCOHOL",

    
    ice1: "Raspberry - Grapefruit",
    taste1: "Bright taste",
    health1: "Revitalizes",
    ice1des: "The combination of two rich flavors and an abundance of vitamins gives vitality and lifts the mood. Raspberries help resist disease, and grapefruit speeds up metabolism.",
    s500ml: "500 ml.",

    ice2: "Pear - Lychee",
    eco1: "Energy booster",
    low1: "Low-Calorie",
    ice2des: 'An explosion of flavorful emotions and ripe sensuality. It’s no wonder lychee<br> is called the fruit of love! The sweetness of juicy pear is delightfully complemented by a cool minty freshness, blending harmoniously with milky<br> oolong and rosebuds.',

    ice3: "Hibiscus - Mango",
    sweetsour1: "Sweet and sour",
    anticold1: "Anti-cold",
    whatcleans1: "Cleansing tea",
    ice3des: 'A rich, sweet flavor is pleasantly balanced by the tangy<br> notes of hibiscus. Packed with vitamin C, it helps protect the body<br> from viral infections, while pectin promotes natural cleansing.',
    
    ice4: "Grape-Jasmine",
    dig1: "Improves digestion",
    anti1: "Antistress",
    ice4des: "One of the most harmonious combinations, both in taste and aroma. It soothes and refreshes, bringing coolness on a hot day.",

    ice5: "Aloe-Apple",
    vit1: "Vitamins",
    imp1: "Improves mood",
    ice5des: "Bright and light, with floral notes in taste and aroma.<br> Beneficial for digestion, improves metabolism, and restores the body’s natural processes.",
    
    ice6: "Nothern Mojito",
    ice6des: "Bright and light, with floral notes in taste and aroma.<br> Beneficial for digestion, improves metabolism, and restores the body’s natural functions.",
    osv1: "Refreshes",
    osv2: "Revitalizes",
    osv3: "Anti-Hangover",

    ice7: "Forest Blueberries",
    ice7des: "A rich and tangy flavor awakens you from fatigue and stimulates brain activity. The blueberry, rich in trace elements, improves digestion and helps lower blood sugar levels.",
    sat1: "Saturated",

    ice8: "Mint Pear",
    ice8des: "Juicy and vibrant, this drink delights with its harmonious blend of refreshing flavors! A detox, antioxidant, and vitamin cocktail — you already know where to find all the freshness of this summer!",
    imu1: "Increases immunity",

      teaAssamName: "Assam",
  teaAssamBrain: "Stimulates brain function",
  teaAssamHeart: "Protects the heart and blood vessels",
  teaAssamDesc: "Strong and astringent, with a vivid malty finish. Tones, energizes, and boosts productivity.",

  teaEarlName: "Earl Grey ",
  teaEarlHeal: "Revitalizes",
  imu1: "Increases immunity",
  teaEarlDesc: "Bergamot has a delicate aroma and a refreshing, invigorating effect.",


  toppingsName: "Toppings / portion",
  toppingsDesc: "Mint, lemon, thyme, ginger, sage, linden flowers, rose petals,<br>currant leaves, honey",

  teaGenmaichaName: "Genmaicha with rice",
  teaGenmaichaDesc: "This tea stands out with its yellow hue and a delicate, airy aroma that intertwines the sweet notes of roasted rice and traditional green tea.",

   teaLungName: "Long-Jing 'Dragon Well'",
  teaLungDesc: "Long Jing is a tea with powerful inner energy. Its flavor ranges from grassy and floral to honey-nutty. Improves mental clarity, structures logic, and sharpens the mind.",
  
  teaBiName: "Bi Luo Chun 'Emerald Spring Spirals'",
  teaBiDesc: "A sweet, delicate taste with honey, fruity, and floral notes. Rich in antioxidants, vitamins, and minerals. Supports heart health, enhances mental and physical performance, and strengthens immunity.",
  
  teaGuanName: "Teguanyin 'Iron Goddess of Mercy'",
  teaGuanHeal: "Tea of a hundred ailments",
  teaGuanHead: "Helps relieve headaches",
  teaGuanDesc: "A stunning aroma of orchid and lilac with a sweet honey flavor.",
  
  teaGinsengName: "Ginseng Oolong",
  teaGinsengVitamins: "Vitamins and microelements",
  teaGinsengHeal: "Promotes wellness",
  teaGinsengDesc: "Light and slightly sweet with mild tart and spicy notes. Lifts mood, increases productivity, and improves focus.",
  
  teaHongName: "Da Hong Pao – Big Red Robe",
  teaHongBones: "Strengthens bones",
  teaHongClean: "Cleanses the body",
  teaHongDesc: "A refreshing tea beneficial for health that provides a relaxing and calming effect on the body.",
  
  teaMilkName: "Milk Oolong",
  teaMilkBurn: "Burns fat",
  teaMilkAntiox: "Antioxidant",
  teaMilkDesc: "A rich milky-creamy taste and delicate aroma of green tea. Activates the body's defenses and helps restore energy.",
  
  teaStrawName: "Emperor’s Strawberry",
  teaStrawDesc: "A beautiful hand-tied tea ball adorned with red clover petals. When brewed, it blossoms into a bright bouquet. The infusion has a light olive hue, with a delicate taste and a subtle floral aroma.",
  
  teaStrawName: "Emperor’s Strawberry",
  teaStrawDesc: "A beautiful hand-tied tea ball adorned with red clover petals. When brewed, it blossoms into a bright bouquet. The infusion has a light olive hue, with a delicate taste and a subtle floral aroma.",
  
  teaLycheeName: "Lychee-Chrysanthemum",
  teaLycheeDesc: "When brewed, it opens into a lush green flower with a yellow chrysanthemum core. The infusion has an ivory color, a fragrant and light aroma, with clear floral notes and the tenderness of green tea.",
  
  teaJasmineName: "Moli Zhen Zhu 'Jasmine Pearls'",
  teaJasmineDesc: "The taste is very light and smooth, slightly sweet with no bitterness, and a fragrant, delicate aroma. It benefits digestion, tones and refreshes in hot weather, warms in the cold, acts as a natural antidepressant, and maintains alertness and good mood.",
  
  teaPuerGoldName: "Pu-erh Golden Premium 2003",
  teaPuerGoldDesc: "Exquisite, rich, and velvety flavor with notes of chocolate and nuts. This tea perfectly invigorates and tones, rich in microelements, beneficial compounds, and vitamins, and also serves as an immune booster.",

  teaChagaoName: "Cha Gao 'Pu-erh Resin'",
  teaChagaoDesc: "Each sip wonderfully energizes, revitalizes, and fills you with Tea Power. It improves health, mood, and brain activity. The taste is soft and deep, without the earthy notes typical of traditional Pu-erh. The aroma is pleasant, smoky, and woody.",

  teaGoldenSnailName: "Te Ji Premium 'Golden Snail'",
  teaGoldenSnailDesc: "A warm, rich, and velvety tea with notes of bread and honey, accented by spices, chocolate, and dried fruits. The taste is juicy, full-bodied, and refined, revealing layers of rye bread, fresh honey, oriental spices, and chocolate.",
  
  teaRooibosName: "Rooibos",
  caffeineFree: "Caffeine-free",
  antiCold: "Anti-cold",
  digImprove: "Improves digestion",
  teaRooibosDesc: "Caffeine-free and suitable for children and nursing mothers. A rich source of antioxidants, often called the Tea of Long Life.",

  // Bael / Matum
  teaBaelName: "Matum / Bael Fruit",
  heartProtect: "Protects the heart",
  digImprove2: "Improves digestion",
  lungsBenefit: "Supports lung health",
  teaBaelDesc: "Caffeine-free and suitable for children and nursing mothers. A rich source of antioxidants, often called the Tea of Long Life.",

  // Blue tea with lavender
  teaBlueLavName: "Blue Tea with Lavender",
  unusual: "Unusual",
  memoryImprove: "Improves memory",
  weightLoss: "Supports weight loss",
  teaBlueLavDesc: "Visitors to Thailand often seek out this tea. Its unique deep color, pleasant aroma, and beneficial properties attract people from all over the world.",

  // Herbal blend
  teaHerbalBlendName: "Herbal collection",
  teaHerbalBlendDesc: "An herbal mix of chamomile blossoms, orange, mallow, lemongrass, mint, citrus peels, and rose hips with a natural orange aroma.",

  // Sagan-Daila
  teaSaganName: "Sagan-Daila (Herb of Happiness)",
  teaSaganDesc: "Boosts the body’s resilience to external factors. Rich in vitamins and vital energy. Sweet-floral taste.",

  // Ivan tea
  teaIvanName: "Ivan Tea (served with honey)",
  teaIvanDesc: "A dense infusion with a deep nut-brown color and a honeyed, lingering aroma. Known as a calming and pain-relieving tea.",
  
  teaWarmingName: "Warming",
  teaWarmingDesc: "An aromatic drink that not only energizes, warms, and helps you relax, but also strengthens immunity and helps fight various ailments.",

  teaMangoPearName: "Mango–Pear",
  teaMangoPearDesc: "Bright in flavor, this tea has great restorative properties and a rich supply of vitamins.",

  teaSeabuckName: "Sea Buckthorn with Orange",
  teaSeabuckDesc: "A wonderfully invigorating, vitamin-rich drink. Packed with vitamins, trace elements, amino acids, and antioxidants.",

  teaGingerLindenName: "Ginger–Linden",
  teaGingerLindenDesc: "Healthy in every way: supports immunity and delights with quince notes combined with ginger, lemon, and linden.",

  teaTropicalName: "Tropical",
  teaTropicalDesc: "A vibrant burst of taste and aroma. Rich in vitamins, beneficial minerals, fiber, and antioxidant elements.",

  teaChrysBananaName: "Chrysanthemum–Banana",
  teaChrysBananaDesc: "Blossoming, bright, and sunny. Perfect for any weather and a good mood.",

  teaRaspberryGingerName: "Raspberry with Ginger",
  teaRaspberryGingerDesc: "The beneficial, potent properties of raspberry and ginger strengthen immunity and improve mood.",

  teaBaiskyName: "Bai Tea",
  teaBaiskyDesc: "A berry-and-fruit tea with a vivid, robust flavor that brings a strong dose of summer vibes.",

  teaPuerJuiceName: "Pu-erh with Juice",
  teaPuerJuiceOption: "Cherry or pomegranate — your choice",
  teaPuerJuiceDesc: "A wonderfully rich and deep flavor. The unusual pairing surprises with layered notes and tones. Also very beneficial—may relieve headaches, strengthen immunity, and provide a pleasant boost of energy.",

  teaMasalaName: "Masala",
  teaMasalaDesc: "A spicy blend of Indian spices and hot milk. This drink boosts your mood and has a strong warming and energizing effect.",

  teaBlueMasalaName: "Blue Masala",
  teaBlueMasalaDesc: "A lighter masala without ginger, yet just as delicious. The mix of Indian spices and hot milk uplifts the mood and warms the body.",

  teaMoroccanName: "Moroccan",
  teaMoroccanDesc: "The aroma of oriental spices enchants, giving a sense of warmth and calm. This wonderful tea enhances concentration and improves blood circulation.",

  plantMilkExtra: "With plant-based milk +100 UAH",

  teaDrunkCherryName: "Drunken Cherry",
  teaDrunkCherryDesc: "",
  
  teaHoneyMulledName: "Honey Mulled Wine",
  teaHoneyMulledDesc: "",
  },

  ua: {
  teaDrunkCherryName: "П'яна вишня",
  teaDrunkCherryDesc: "",

  teaHoneyMulledName: "Медовий глінтвейн",
  teaHoneyMulledDesc: "",

  teaMasalaName: "Масала",
  teaMasalaDesc: "Пікантне поєднання Індійських спецій і гарячого молока, напій підвищує настрій і володіє сильним зігріваючим і тонізуючим ефектом.",

  teaBlueMasalaName: "Блакитна Масала",
  teaBlueMasalaDesc: "Легка масала без імбиру, але все така ж смачна. Завдяки поєднанню індійських спецій і гарячого молока піднімає настрій і зігріває тіло.",

  teaMoroccanName: "Мароканський",
  teaMoroccanDesc: "Аромат східних спецій причаровує, дає відчуття тепла і спокою. Цей дивовижний чай підвищить концентрацію і покращить кровообіг.",

  plantMilkExtra: "На рослинному молоці + 100 грн",

  teaWarmingName: "Зігріваючий",
  teaWarmingDesc: "Ароматний напій не тільки збагачує енергією, зігріває і дозволяє розслабитися, але і зміцнює імунітет і допомогає боротися з різними захворюваннями.",

  teaMangoPearName: "Манго - груша",
  teaMangoPearDesc: "Яскравий по своєму смаку, чай має хороші відновні властивості і великий запас вітамінів.",

  teaSeabuckName: "Обліпиха з апельсином",
  teaSeabuckDesc: "Чудовий повний вітамінів тонізуючий напій. Цей чай неймовірно корисний, в ньому містяться вітаміни, мікроелементи, амінокислоти, антиоксиданти.",

  teaGingerLindenName: "Імбир-липа",
  teaGingerLindenDesc: "Корисний у всіх сенсах, підтримає імунітет та порадує смаком айви у поєднанні з імбирем, лимоном та липою.",

  teaTropicalName: "Тропічний",
  teaTropicalDesc: "Яскрава феєрія смаку та аромата. Чай багатий на вітаміни, корисні мінерали, клітковину та антиоксидантні елементи.",

  teaChrysBananaName: "Хризантема-банан",
  teaChrysBananaDesc: "Квітучий, яскравий та сонячний. Для будь-якої погоди і гарного настрою.",

  teaRaspberryGingerName: "Малиновий з імбирем",
  teaRaspberryGingerDesc: "Корисні і сильні лікувальні властивості малини і імбиру зміцнять імунітет і поліпшать настрій.",

  teaBaiskyName: "Байський чай",
  teaBaiskyDesc: "Ягідно-фруктовий чай з яскравим та сильним смаком. Приносить сильний заряд літнього настрою.",

  teaPuerJuiceName: "Пуер на соку",
  teaPuerJuiceOption: "Вишневий або гранатовий на вибір",
  teaPuerJuiceDesc: "Дивовижно багатий та глибокий смак. Незвичне поєднання вражає уяву смаковитими нотами та відтінками. Крім того, напій дуже корисний - здатний позбавити головного болю, зміцнити імунітет, добре збадьорити організм.",


  
  // Ройбуш
  teaRooibosName: "Ройбуш",
  caffeineFree: "Без кофеїна",
  antiCold: "Анти-застуда",
  digImprove: "Покращує травлення",
  teaRooibosDesc: "Не містить кофеїн і підходить для дітей і матерів-годувальниць. Є багатим джерелом анти-оксидантів. Його навіть називають Чаєм Довгого Життя.",

  // Матум / Баель
  teaBaelName: "Матум / Плоди Дерева Баель",
  heartProtect: "Захищає серце",
  digImprove2: "Покращує травлення",
  lungsBenefit: "Для легень",
  teaBaelDesc: "Не містить кофеїн і підходить для дітей і матерів-годувальниць. Є багатим джерелом анти-оксидантів. Його навіть називають Чаєм Довгого Життя.",

  // Блакитний чай з лавандою
  teaBlueLavName: "Блакитний чай з лавандою",
  unusual: "Незвичайний",
  memoryImprove: "Покращує пам'ять",
  weightLoss: "Сприяє похуданню",
  teaBlueLavDesc: "Туристи, які гостюють в Тайланді, неодмінно шукають там цей чай. Його незвичайний насичений колір та приємний аромат, а також корисні властивості, приваблюють людей з усього світу.",

  // Трав'яний збір
  teaHerbalBlendName: "Трав'яний збір",
  teaHerbalBlendDesc: "Трав'яна суміш із суцвіть ромашки, апельсина, мальви, лимонної трави, м'яти, шкірки цитрусових і шипшини. З натуральним ароматом апельсина.",

  // Саган-Дайля
  teaSaganName: "Саган-Дайля (Трава щастя)",
  teaSaganDesc: "Підвищує опірність організму до навколишньої дійсності. Насичений вітамінами і силами для життя. Смак солодкувато-квітковий.",

  // Іван чай
  teaIvanName: "Іван чай (подається з медом)",
  teaIvanDesc: "Густий настій темно-горіхового кольору, ароматний з медовими, тягучими нотками. Чай вважається прекрасним заспокійливим і болезаспокійливим засобом.",
  
  teaGoldenSnailName: "Те Цзи 'Золотий Равлик' Преміум",
  teaGoldenSnailDesc: "Теплий, соковитий і оксамитовий чай з хлібно-медовими нотками, з нюансами спецій, шоколаду та сухофруктів. Смак соковитий, об'ємний, витончений, з властивою солодощі і переливається відтінками житнього хліба, свіжого меду, східних прянощів і шоколаду.",
  
  teaPuerGoldName: "Пу Ер Золотий Преміум 2003 г",
  teaPuerGoldDesc: "Вишуканий, насичений, маслянистий, майже бархатистий смак з нотками шоколаду і горіха. Напій прекрасно бадьорить і тонізує, багатий багатьма мікроелементами, корисними речовинами і вітамінним комплексом, а також служить стимулятором імунітету.",

  teaChagaoName: "Ча Гао 'Смола Пуеру'",
  teaChagaoDesc: "Кожен ковток чудово тонізує, бадьорить, заряджає енергією і Чайною Силою, покращує здоров'я, настрій, активізує роботу мозку. Смак м'який, глибокий. Без землянистого присмаку, характерного для традиційного пуеру. Аромат приємний, димно-деревний.",


  teaJasmineName: "Молі чжень Чжу 'Жасмінова Перлина'",
  teaJasmineDesc: "Смак дуже легкий і м'який, солодкуватий, відсутня терпкість, аромат запашний і ніжний. Сприятливо впливає на травну систему, тонізує і освіжає в жарку пору року і зігріває в холод, є хорошим антидепресантом, підтримує бадьорий стан і гарний настрій.",
  

  teaStrawName: "Полуниця Імператора",
  teaStrawDesc: "Чудовий пов'язаний чай у вигляді кульки, прикрашений пелюстками червоної конюшини. При заварюванні розпускається яскравим букетом. Настій світло-оливкового кольору, смак ніжний з тонким ароматом квітів.",
  
  teaLycheeName: "Лічі Хризантема",
  teaLycheeDesc: "При заварюванні розпускається пишна, величезна зелена квітка з жовтою серцевиною з ніжних хризантем. Настій кольору слонової кістки, ароматний, легкий. У смаку чітко відчувається квіткова нота та ніжність зеленого чаю.",
  
  
    teaGenmaichaName: "Генмайча / смажений з рисом",
  teaGenmaichaDesc: "Напій відрізняється жовтим відтінком і дуже м'яким повітряним ароматом, в якому переплелися солодкуваті нотки обсмаженого<br> рису і традиційного зеленого чаю.",

teaLungName: "Лун Цзин Преміум",
  teaLungDesc: "Лун цзин — чай з потужною внутрішньою силою. Смак варіюється від трав'яного і квіткового до медово-горіхового. Покращує розумові процеси, структурує логіку, прояснює свідомість, робить розум чітким і ясним.",
  
  teaBiName: "Бі Ло Чунь Преміум",
  teaBiDesc: "Напій має солодкий ніжний смак з медовими, фруктовими і квітковими відтінками. Багатий антиоксидантами, вітамінами і мінералами, зміцнює імунітет та сприяє профілактиці серцево-судинних захворювань.",
  
  teaGuanName: "Те гуань Інь 'Залізна Богиня'",
  teaGuanHeal: "Чай від ста хвороб",
  teaGuanHead: "Допоможе при головних болях",
  teaGuanDesc: "Приголомшливий аромат орхідеї і бузку, солодкий медовий смак.",
  
  teaGinsengName: "Женьшеневий улун",
  teaGinsengVitamins: "Вітаміни та мікроелементи",
  teaGinsengHeal: "Оздоровлює",
  teaGinsengDesc: "Легкий і солодкуватий, але злегка терпкий і пряний смак. Піднімає настрій, підвищує працездатність і концентрацію уваги.",
  
  teaHongName: "Да хун пао. Великий червоний халат",
  teaHongBones: "Укріпляє кістки",
  teaHongClean: "Очищує організм",
  teaHongDesc: "Корисний для здоров'я освіжаючий чай, який надає розслабляючу і заспокійливу дію на організм.",
  
  teaMilkName: "Молочний улун",
  teaMilkBurn: "Сжигає жири",
  teaMilkAntiox: "Антиоксидант",
  teaMilkDesc: "Виражений молочно-вершковий смак і тонкий аромат зеленого чаю. Прекрасно активує захісні функції організму, сприяє відновленню сил.",
  



    Menu: "МЕНЮ",
    Bar: "БАР",
    Tea_Card: "ЧАЙНА КАРТА",
    Wine_card: "ВИННА КАРТА",
    CHI_SOUCE_EGGPLANT: "БАКЛАЖАН З СОУСОМ ЧІ",
    new_in: "НОВИНКИ",
    nigiri: "СУШІ НІГІРІ",
    sashimi: "САШИМІ",
    gunkan: "ГУНКАН",
    temaki: "ТЕМАКІ",
    rolls: "РОЛИ",
    salads: "САЛАТИ",
    coldap: "ХОЛОДНІ ЗАКУСКИ",
    soups: "СУПИ",
    hotap: "ГАРЯЧІ ЗАКУСКИ",
    hotsea: "ГАРЯЧІ ЗАКУСКИ З МОРЕПРОДУКТІВ",
    dimsum: "ДИМ САМ",
    gyoza: "ГЕЗА",
    sides: "ГАРНІРИ",
    hotd: "ГАРЯЧІ СТРАВИ",
    fish: "РИБА",
    desserts: "ДЕСЕРТИ",
    candie: "ЦУКЕРКИ",
    new2: "НОВИНКИ",
    muss: "МІДІЇ В СОУСІ ВАСАБІ",
    eggpl: "САЛАТ З БАКЛАЖАНАМИ ТА ТОМАТАМИ",
    CIBAS: "ЧИЛІЙСЬКИЙ СІБАС З МІСО СОУСОМ",
    SWEETPOTATO: "БАТАТ ФРІ З ТРЮФЕЛЬНИМ СОУСОМ ТА ПАРМЕЗАНОМ",
    MISOSPICY: "СУП МІСО СПАЙСІ",
    nig0: "СУШІ НІГІРІ", 
    nig1: "ЛОСОСЬ",
    nig2: "ТУНЕЦЬ",
    nig3: "ІКРА ЛЕТЮЧОЇ РИБИ",
    nig4: "КРЕВЕТКА ТИГРОВА",
    nig5: "ВУГОР",
    nig6: 'ХРУСТКИЙ РИС З ГОСТРИМ ТУНЦЕМ <img class="spicy" src="img/Spicy.svg" style="padding-left:5px;">',
    nig6des: "Тунець, томат чері, цибуля шалот, ікра летючої риби, японський майонез, чілі Гуйлін",
    nig7: 'ХРУСТКИЙ РИС З ГОСТРИМ ЛОСОСЕМ <img class="spicy" src="img/Spicy.svg" style="padding-left:5px;">',
    nig7des: "Лосось, томат чері, цибуля шалот, ікра летючої риби, японський майонез, чілі Гуйлін",
    sash0: "САШИМІ",
    sash1: "ЛОСОСЬ",
    sash2: "ВУГОР",
    sash3: "ТУНЕЦЬ",
    sash4: "МОРСЬКИЙ ГРЕБІНЕЦЬ",
    sash5: "КРЕВЕТКА ТИГРОВА",
    gunk0: "ГУНКАН",
    gunk1: "ЛОСОСЬ",
    gunk1des: "Лосось, ікра летючої риби, японський майонез",
    gunk2: "ТУНЕЦЬ",
    gunk2des: "Тунець, ікра летючої риби, японський майонез",
    gunk3: "КРЕВЕТКА ТИГРОВА",
    gunk3des: "Креветка, ікра летючої риби, японський майонез, авокадо",
    gunk4: "ГРЕБІНЕЦЬ",
    gunk4des: "Морський гребінець, ікра летючої риби, японський майонез",
    gunk5: "КРАБ",
    tem0: "ТЕМАКІ (HAND ROLL) <br> У ЛИСТІ НОРІ/В СОЄВОМУ ЛИСТІ",
    tem1: "ЛОСОСЬ",
    tem1des: "Лосось, ікра летючої риби, японський майонез",
    tem2: "ТУНЕЦЬ",
    tem2des: "Тунець, ікра летючої риби, японський майонез",
    tem3: "КРЕВЕТКА ТИГРОВА",
    tem3des: "Креветка, ікра летючої риби, японський майонез",
    tem4: "ГРЕБІНЕЦЬ",
    tem4des: "Морський гребінець, ікра летючої риби, японський майонез",
    tem5: "КРАБ",
    rol0: "РОЛИ",
    rol1: "РОЛ З ВУГРЕМ",
    rol1des: "Вугор, авокадо, огірок, кунжут, унагі соус",
    rol2: "ФІЛАДЕЛЬФІЯ ДЕ ЛЮКС",
    rol2des: "Лосось, сир філадельфія, вугор, авокадо",
    rol3: "ФІЛАДЕЛЬФІЯ КЛАСИЧНА",
    rol3des: "Лосось, сир філадельфія, авокадо",
    rol4: "ЗОЛОТИЙ ДРАКОН",
    rol4des: "Вугор, тунець, ікра летючої риби, унагі соус, кунжут",
    rol5: "НОРВЕЖСЬКИЙ ЛОСОСЬ З ТИГРОВОЮ КРЕВЕТКОЮ",
    rol5des: "Креветки темпура, авокадо, лосось, соус трюфельний",
    rol6: "КАЛІФОРНІЯ З КРАБОМ",
    rol6des: "Крабове м'ясо, авокадо, огірок, ікра летючої риби, японський майонез",
    rol7: "КРАНЧ РОЛ З КРЕВЕТКОЮ",
    rol7des: "Креветка, огірок, унагі соус, японський майонез, ікра летючої риби, темпура",
    rol8: "РОЛ З КРАБОМ І АВОКАДО",
    rol8des: "Крабове м'ясо, ікра летючої риби, авокадо, унагі",
    rol9: "РОЛ ФУТОМАКІ",
    rol9des: "Креветка темпура, вугор, лосось, сир філадельфія, ікра летючої риби",
    rol10: "КАЛІФОРНІЙСЬКИЙ РОЛ З ЛОСОСЕМ",
    rol10des: "Лосось, ікра летючої риби, трюфельний соус, огірок, авокадо",
    rol11: "МУН РОЛ",
    rol11des: " Лосось копчений, сир філадельфія, авокадо, огірок, ікра летючої риби",
    rol12: "РОЛ DOUBLE FISH",
    rol12des: "Смажений лосось, вугор, авокадо, сир філадельфія, ікра летючої риби",
    sal0: "САЛАТИ",
    sal1: "САЛАТ ХИЯШИ ВАКАМЕ З ГОРІХОВИМ СОУСОМ",
    sal2: "ТЕПЛИЙ САЛАТ ІЗ ТЕЛЯТИНИ ПО ТАЙСЬКИ",
    sal2des: "Мікс салатів, перець болгарський, гриби шиітаки, ніжна телятина, соєві паростки, чілі перець, імбирний сироп",   
    sal3: "САЛАТ З ЛОСОСЕМ",
    sal3des: "Лосось татаки, селера, яблуко, арахіс, мікс салатів, часникові чіпси, фірмовий соус",
    sal4: "САЛАТ МАКОТО",
    sal4des: "М'ясо краба, соус васабі, огірок, авокадо",
    sal5: "РУКОЛА & КРЕВЕТКА",
    sal5des: "Креветки, томати чері, грецькі горіхи, фірмовий соус",
    sal6: "САЛАТ З ВУГРЕМ ТА ГРУШЕЮ",
    sal6des: "Вугор, авокадо, гостра груша, шпинат, горіховий соус, горіх",
    sal7: "САЛАТ З МОРЕПРОДУКТАМИ ТА ФРУКТОЮ",
    sal7des: "Креветка, лосось, кальмар, сезонна фрукта, селера, перець болгарський, базилік, морква, фірмовий соус",
    coldap0: "ХОЛОДНІ ЗАКУСКИ",
    coldap1: "ТАР-ТАР ЛОСОСЬ З ГУАКАМОЛЕ",
    coldap1des: "Лосось, японський майонез, авокадо, томат чері, мікрозелень, ікра летючої риби, юзу",
    coldap2: "ТАР-ТАР АЗУМА",
    coldap2des: "Лосось, тунець, гуакамоле юзу, японський майонез, томат чері, ікра летючої риби, креветочні чіпси",
    coldap3: "ТАР-ТАР З ГРЕБІНЦЯ",
    coldap3des: "Свіжий гребінець, японський майонез, ікра летючої риби, авокадо, мікрозелень, чілі перець",
    coldap4: "ТАР-ТАР З МАРИНОВАНОЇ ТЕЛЯТИНИ",
    coldap5: "ОВОЧІ З ГОРІХОВИМ СОУСОМ",
    soup0: "СУПИ",
    soup1: "МІСО СУП",
    soup1des: "Насичений бульйон, лосось, сир Тофу, шиітаке, вакаме, кунжут, зелена цибуля",
    soup2: '* СУП З МОРЕПРОДУКТІВ НА КОКОСОВОМУ МОЛОЦІ <img src="img/Extra.svg" style="padding-left: 5px;">',
    soup2des: "Кокосове молоко, тигрова креветка, червоний окунь, галангал, лист лайму, чілі перець, лимонграс, печериці, паровий рис",
    soup3: "* ФО БО",
    soup3des: "В'єтнамський пряний суп з телятиною та локшиною",
    soup4: 'КРАБОВИЙ СУП "КАНІ НАБЕ"',
    soup5: "* ТОМАТНИЙ СУП З МОРЕПРОДУКТАМИ",
    soup5des: "Рибний бульйон, гострий томатний соус, морський гребінець, судак, креветка тигрова, лосось, морський окунь, кальмар",
    hotap0: "ГАРЯЧІ ЗАКУСКИ",
    hotap1: "СПРИНГ РОЛ З ОВОЧАМИ",
    hotap1des: "Капуста, морква, печериці, соус з цибулі",
    hotap2: "СПРИНГ РОЛ З КАЧКОЮ",
    hotap2des: "Пекінська качка, морква, корінь селери, гриби шиітаке, цибуля-порей, болгарський перець, соус хойсин",
    hotap3: 'ЕДАМАМЕ <img class="spicy" src="img/Spicy.svg" style="padding-left: 5px;"',
    hotap3des: 'Японські боби, морська сіль <br> "гострі / солоні" за бажанням',
    dimsum0: "ДИМ САМ NEW STYLE",
    dimsum1: "СІОМАЙ З ГРЕБІНЦЕМ ТА ЛОСОСЕМ",
    dimsum1des: "Морський гребінець, лосось, цибуля-порей, кокосове молоко",
    dimsum2: "СІОМАЙ З МОРСЬКИМ ГРЕБІНЦЕМ ТА ЧЕРВОНОЮ ІКРОЮ",
    dimsum2des: "Морський гребінець та тигрова креветка, яйце",
    dimsum3: "* СІОМАЙ З КРАБОМ ТА ШПІНАТОМ",
    dimsum3des: "Краб, шпинат, креветка, імбир, соус з устриць, рослинна олія, кунжутна олія",
    dimsum4: "ДАМПЛІНГ З ЛОСОСЕМ, ЗЕЛЕНОЮ ЦИБУЛЕЮ ТА ІКРОЮ ЛЕТЮЧОЇ РИБИ",
    dimsum4des: "Лосось та зелена цибуля",
    dimsum5: "ДАМПЛІНГ З БІЛИХ РИБ",
    dimsum5des: "Судак, сибас, дорадо, соус шрірача",
    dimsum6: "ДАМПЛІНГ АСОРТІ",
    dimsum6des: "Шпинат - креветка, курка - шиітаке, лосось - зелена цибуля, з білих риб, качка",
    dimsum7: "ДАМПЛІНГ З КРЕВЕТКОЮ ТА ЦИБУЛЕЮ ПОРЕЙ",
    dimsum7des: "Свіжий шпинат та тигрова креветка",
    dimsum8: "ДАМПЛІНГ З КРОЛИКОМ",
    hotapf0: "ГАРЯЧІ ЗАКУСКИ З МОРЕПРОДУКТІВ",
    hotapf1: "ЕБІ ТЕМПУРА",
    hotapf1des: "Тигрова креветка з традиційним соусом темпура",
    hotapf2: "МИГДАЛЬНІ КРЕВЕТКИ",
    hotapf2des: "Тигрові креветки у мигдальних пластівцях",
    hotapf3: "ПОПКОРН З КРЕВЕТОК",
    gyoza0: "ГЕЗА",
    gyoza1: "ГЕЗА З КУРКОЮ",
    gyoza1des: "Курка, цибуля-порей, зелена цибуля",
    gyoza2: "ГЕЗА ЗІ СВИНИНОЮ ТА КРЕВЕТКОЮ",
    gyoza2des: "Свинина, креветка, зелень",
    gyoza3: "ГЕЗА З ТЕЛЯТИНОЮ ТА КРЕВЕТКОЮ",
    gyoza3des: "Телятина, креветка, зелень",
    side0: "ГАРНІРИ",
    side1: "ГОХАН",
    side1des: "Рис паровий білий",
    side2: "ЯКИ МЕШИ",
    side2des: "Рис з грибами шиітаке, печерицями, морквою, зеленим горошком",
    side3: "ГРИБИ У КИТАЙСЬКОМУ СТИЛІ",
    side4: "ТРАФЛ ФРАЙЗ",
    side4des: "З Сичуанським перцем та трюфелним соусом",
    side5: "СПАРЖА ГРИЛЬ",
    hotdd0: "ГАРЯЧІ СТРАВИ",
    hotdd1: "ТЕЛЯТИНА З КОРЕНЕМ ЛОТОСА",
    hotdd1des: "Злегка хрумка телятина приготована в wok з соусом теріякі та коренем лотоса",
    hotdd2: "МЕДАЛЬЙОНИ З ТЕЛЯТИНИ В СОУСІ ТЕРІЯКІ",
    hotdd3: "РИС В ТАЙСЬКОМУ СТИЛІ",
    hotdd3des: "Рис з міксом із зелені, креветкою, соєвим соусом, приготований wok",
    hotdd4: "РИСОВА ЛОКШИНА З ТИГРОВИМИ КРЕВЕТКАМИ ТА ОВОЧАМИ",
    hotdd5: 'РИСОВА ЛОКШИНА З КАЧКОЮ ПО-ПЕКІНСЬКИ <img class="spicy" src="img/Spicy.svg" style="padding-left: 5px;">',
    hotdd6: 'КОНГБАО <img class="spicy" src="img/Spicy.svg" style="padding-left: 5px;">',
    hotdd6des: "Курка з овочами та спаржею у соусі Чілі",
    hotdd7: "ЛАПША УДОН З ТЕЛЯТИНОЮ",
    hotdd7des: "Лапша удон, телятина, овочі",
    hotdd8: "КРЕВЕТКА У КИСЛО-СОЛОДКОМУ СОУСІ З АНАНАСОМ",
    hotdd8des: "Тигрові креветки обсмажені з овочами та ананасом",
    hotdd9: "КАЧКА ПО-ПЕКІНСЬКИ",
    hotdd9des: "Традиційна качка, огірки свіжі, цибуля, млинці, соус хойсин",
    hotdd10: "КУРЧА ТЕРІЯКІ",
    hotdd11: "КРЕВЕТКИ ГРИЛЬ",
    hotdd12: "ПЕРУАНСЬКІ РЕБРА",
    hotdd12des: " Манго, чилі, соус унаги гострий",
    hotdd13: "СТЕЙК ТЕЛЯТИНА",
    hotdd14: "ГРЕБІНЕЦЬ ГРИЛЬ",
    fisch0: "РИБА",
    fisch1: "ЛОСОСЬ ТЕРІЯКІ",
    fisch1des: "Лосось обсмажений в соусі теріякі",
    fisch2: "СУДАК НА ГРИЛІ З ЧАСНИКОВИМ СОУСОМ",
    fisch3: "ДОРАДО ТЕРІЯКІ З ЧЕРІ",
    dess0: "ДЕСЕРТИ",
    dess1: 'ТРУБОЧКА "ФІЛО" З ЯГОДАМИ ТА КРЕМОМ МАСКАРПОНЕ',
    dess2: "ОРІХОВО-ШОКОЛАДНИЙ ДЕСЕРТ",
    dess3: "ФІРМОВИЙ НАПОЛЕОН",
    dess4: "КРЕМ-БРЮЛЕ З ЮЗУ",
    dess5: "ЯБЛУЧНИЙ ТАРТ",
    dess6: "ШОКОЛАДНИЙ ФОНДАН",
    dess7: "СОРБЕТ ЛАЙМ",
    dess8: "СОРБЕТ МАНГО",
    dess9: "СОРБЕТ ЯГІДНИЙ",
    dess10: "МОРОЗИВО В АСОРТИМЕНТІ",
    candie0: "ЦУКЕРКИ",
    candie1: "РОЯЛТІН",
    candie2: "ВИШНЯ В ШОКОЛАДІ",
    candie3: "ПРАЛІНЕ З ФУНДУКОМ",
    candie4: "БАМБУК",
    candie5: "ДУБАЙСЬКИЙ ШОКОЛАД",
    s50ml : "50 мл",
    work1: "Робочiй час:",
    add1: "Адреса:",
    phone1: "Телефон:",
    s11: "САКЕ",
    s12: "ГОРІЛКА",
    s13: "ВИНОГРАДНА ГОРІЛКА",
    s14: "ЯПОНСЬКИЙ ДЖИН",
    s15: "ДЖИН",
    s16: "ТЕКІЛА",
    s17: "РОМ",
    s18: "КОНЬЯК",
    s19: "КАЛЬВАДОС",
    s20: "ЯПОНСЬКИЙ ВІСКІ",
    s21: "АМЕРИКАНСЬКИЙ ВІСКІ",
    s22: "АМЕРИКАНСЬКИЙ ВІСКІ ТЕНЕСІ",
    s23: "БУРБОН",
    s24: "ШОТЛАНДСЬКИЙ ВІСКІ",
    s25: "ШОТЛАНДСЬКИЙ ВІСКІ ОДНОСОЛОДОВИЙ",
    s26: "ІРЛАНДСЬКИЙ ВІСКІ",
    s27: "ЛІКЕРИ",
    s28: "НАСТОЯНКИ",
    s29: "ВЕРМУТ",
    s30: "ШОТИ",
    s31: "ПИВО",
    s32: "КОКТЕЙЛІ АЛКОГОЛЬНІ",
    s33: "ГАРЯЧІ НАПОЇ",
    s34: "БЕЗАЛКОГОЛЬНІ НАПОЇ",
    s35: "СВІЖОВИДАВЛЕНІ СОКИ",
    s36: "КОКТЕЙЛІ БЕЗАЛКОГОЛЬНІ",
    s37: "ЛИМОНАДИ",
    s300ml: "330 мл",
    drink1: "Еспресо / Еспресо без кофеїну",
    drink2: "Американо / Американо без кофеїну",
    drink3: "Капучіно / Капучіно без кофеїну",
    drink4: "Лате Макіато",
    drink5: "Матча Лате (на рослинному молоці)",
    drink6: "Допіо (на рослинному молоці)",
    drink7: "Кава по-турецьки",
    drink8: "Какао з маршмелоу",
    drink9: "Раф кава",
    drink9_desc: "Кава збита з вершками та сиропом крем-брюле",
    drink10: "Флет Уайт",
    drink10_desc: "Подвійний еспресо, молоко",
    drink11: "Еспресо-Тонік",
    drink11_desc: "Еспресо, тонік, сироп маракуя",
    drink12: "Глінтвейн червоний/білий",
    drink12_desc: "Вино, мед, спеції",
    drink13: "Вода мінеральна Aqua Panna",
    drink13_desc: "250 мл, негазована",
    drink14: "Вода мінеральна Rocchetta",
    drink14_desc: "500 мл, негазована, газована",
    drink15: "Вода мінеральна Evian",
    drink15_desc: "750 мл",
    drink16: "Вода мінеральна Perrier",
    drink16_desc: "330 мл",
    drink17: "Вода мінеральна Borjomi",
    drink17_desc: "500 мл",
    drink18: "Organic Fritz Cola Sugar Free",
    drink18_desc: "330 мл",
    drink19: "Coca-Cola, Sprite",
    drink19_desc: "250 мл",
    drink20: "Тонік Original",
    drink20_desc: "300 мл",
    drink21: "Сік в асортименті",
    drink21_desc: "250 мл",
    juice1: "Ананасовий",
    juice1_desc: "300 мл",
    juice2: "Яблучний",
    juice2_desc: "300 мл",
    juice3: "Моркв'яний",
    juice3_desc: "300 мл",
    juice4: "Грейпфрутовий",
    juice4_desc: "300 мл",
    juice5: "Апельсиновий",
    juice5_desc: "300 мл",
    lemon1: "Лимонад БаблГам-Полуниця",
    lemon1_desc: "400 мл",
    lemon2: "Лимонад Лічі-Малина",
    lemon2_desc: "400 мл",
    lemon3: "Лимонад Груша-Бергамот",
    lemon3_desc: "400 мл",
    lemon4: "Лимонад Ананас-Яблуко",
    lemon4_desc: "400 мл",
    lemon5: "Лимонад Кавун-Юзу",
    lemon5_desc: "400 мл",
    lemon6: "Лимонад Огірок-Маракуйя",
    lemon6_desc: "400 мл",
    lemon7: "Лимонад Фіалка-Бузина",
    lemon7_desc: "400 мл",

    t1:  "ОСВІЖАЮЧІ ЧАЇ",
    t2:  "ЧОРНІ ЧАЇ",
    t3:  "ЯПОНСЬКИЙ ЧАЙ",
    t4:  "КИТАЙСЬКІ ЕЛІТНІ ЧАЇ",
    t5:  "ПОВ'ЯЗАНІ ЧАЇ",
    t6:  "ЖАСМІНОВИЙ ЧАЙ",
    t7:  "ПУЕР",
    t8:  "ЧЕРВОНИЙ ЧАЙ",
    t9:  "ТРАВ'ЯНІ ЧАЇ",
    t10: "ФРУКТОВО-ЯГІДНІ ЧАЇ",
    t11: "ЕКЗОТИЧНІ ЧАЇ",
    t12: "АЛКОГОЛЬНІ ЧАЇ",

    ice1: "Малина - Грейпфрут",
    taste1: "Яскравий смак",
    health1: "Оздоровлює",
    ice1des: "Поєднання двох насичених смаків і достаток вітамінів надає бадьорості і підніме настрій. Малина допомогає потистояти <br> хворобам, а грейпфрут прискорити обмін речовини.",
    s500ml: "500 мл.",

    ice2: "Груша - Лічі",
    eco1: "Еко-енергетик",
    low1: "Низько-калорійний",
    ice2des: 'Вибух смакових емоцій і стиглої чуттєвості. Не дарма лічі<br> називають плодами кохання! Солодкість соковитої груші приємно доповнена холодно-м’ятною свіжістю: в поєднанні з молочним<br> улун і бутонами троянд.',
    
    ice3: "Каркаде - Манго",
    sweetsour1: "Солодко-кислий",
    anticold1: "Анти-застуда",
    whatcleans1: "Що очищає",
    ice3des: 'Щільний і солодкий смак приємно оттеняється кислуватими <br> нотками каркаде. Велика кількість вітаміну С захищає організм <br> від вірусних інфекцій, а пектин сприяє очищенню організму.',
    
    ice4: "Виноград - Жасмин",
    dig1: "Покращує травлення",
    anti1: "Знімає стрес",
    ice4des: "Одне з найбільш гармонійних поєднань як у смаку, так і в ароматі. Заспокоїть і подарує  прохолоду в спекотний день.",
    
    ice5: "Алое - Яблуко",
    vit1: "Вітаміни",
    imp1: "Покращує настрій",
    ice5des: "Яскравий і легкий, з квітковими нотками в смаку і ароматі.<br> Корисний для травлення, покращує обмін речовин і відновлює процеси організму.",
  
    ice5: "Північний Мохіто",
    ice5des: "Яскравий і легкий, з квітковими нотками в смаку і ароматі.<br> Корисний для травлення, покращує обмін речовин і відновлює процеси організму.",
    osv1: "Освіжає",
    osv2: "Оздоровлює",
    osv3: "Анти-похмілля",

    ice7: "Лісова Чорниця",
    ice7des: "Терпкий та щільний смак пробуджує від втоми, стимулює мозкову діяльність. Багата на мікроелементи чорниця покращує травлення та знижує рівень цукру у крові.",
    sat1: "Насичений",

    ice8: "М'ятний Дюшес",
    ice8des: "Соковитий та яскравий, цей напій дивує гармонійним поєднанням смаків, які збадьорують! Детокс, антиоксидант, і вітамінний коктейль: ви вже знаєте, де знайти усю свіість цього літа!",
    imu1: "Підвищує імунітет",

    teaAssamName: "Ассам Бехора",
  teaAssamBrain: "Стимулює роботу мозку",
  teaAssamHeart: "Захищає серце і судини",
  teaAssamDesc: "Сильний, терпкий з яскравим солодовим присмаком. Тонізує, заряджає енергією і підвищує працездатність.",

   teaEarlName: "Ерл Грей Преміум",
  teaEarlHeal: "Оздоровлює",
  imu1: "Підвищує імунітет",
  teaEarlDesc: "Бергамот володіє чудовим тонким ароматом і має тонізуючий ефект.",

  toppingsName: "Топінги / порція",
  toppingsDesc: "М'ята, лимон, чебрець, імбир, шавлія, квітки липи, квітки троянди,<br>лист смородини, мед",
  
  },
};

// === Применение перевода ===
function applyTranslations(lang) {
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    const translation = translations[lang]?.[key];
    if (translation) el.innerHTML = translation;
  });
}

// === Сохранение выбранного языка ===
function setLanguage(lang) {
  localStorage.setItem("lang", lang);
  applyTranslations(lang);
}

// === При загрузке страницы применяем сохранённый язык ===
document.addEventListener("DOMContentLoaded", () => {
  const savedLang = localStorage.getItem("lang") || "ua";
  applyTranslations(savedLang);
  updateLangButtons(savedLang);

  document.getElementById("lang-ua")?.addEventListener("click", () => {
    setLanguage("ua");
    updateLangButtons("ua");
  });

  document.getElementById("lang-en")?.addEventListener("click", () => {
    setLanguage("en");
    updateLangButtons("en");
  });
});

// Функция для визуального состояния кнопок
function updateLangButtons(activeLang) {
  const uaBtn = document.getElementById("lang-ua");
  const enBtn = document.getElementById("lang-en");

  if (!uaBtn || !enBtn) return;

  uaBtn.classList.toggle("active", activeLang === "ua");
  enBtn.classList.toggle("active", activeLang === "en");
}

